# Generated by Django 6.1 on 2026-08-28 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy_at_generation', models.FloatField(help_text='The accuracy percent (0-100) that triggered this recommendation.')),
                ('explanation', models.TextField(help_text='Short, targeted explanation of the concept the student is struggling with.')),
                ('practice_prompt', models.TextField(help_text='A new practice question generated to address the weak topic.')),
                ('practice_choices', models.JSONField(help_text='List of {"text": str, "is_correct": bool} generated answer choices.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='learning.topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
